services:
  web:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  api:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/
  sqlite3:
    image: nouchka/sqlite3:latest

